### ISSUE TITLE
Fail to build vSRX

### ISSUE THREAD

**Issue by tagur87** [carlmontanari/boxen#2]
Hey @carlmontanari

Me again. :) Hope you don't mind more issues.

Here's an error i'm getting when trying to build the docker images it seems.

```boxen package --disk media-vsrx-vmdisk-20.3R3.8.qcow2                                 
      info   1641237602 package requested for disk 'media-vsrx-vmdisk-20.3R3.8.qcow2'
      info   1641237637 docker build output available at '/var/folders/db/h649qj4d0s1f5gqprxb2lx9c0000gn/T/boxen947006849/initial_build.log'
  critical   1641237769 error starting build container: exit status 1
  critical   1641237769 error building base image: exit status 1
        🆘 finished unsuccessfully in 167 seconds 
```

I tailed out the initial_build.log during the build process, but this is all I get, seems to get stuck here.

```
#10 [6/7] RUN bash -c "$(curl -sL https://raw.githubusercontent.com/carlmontanari/boxen/main/get.sh)" -- -v 0.0.0
#10 sha256:5e256bc9ad51e8e203ec01aa0d4250ba1337b06a263889f6e7ee1553f34794ab
#10 CACHED

#11 [7/7] RUN curl http://172.19.233.117:6666/disk.qcow2 -o disk.qcow2
#11 sha256:c58110c498c822f41300a951b2b9602bd964e1412a274fe1e95bee4f99a6e566
#11 0.290   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#11 0.297                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:48 --:--:--     0^C
```

Any advice where in the code to start looking? I know a little Go so, I'd be willing to help contribute, but might need some direction on where to look. :)

**Comment by carlmontanari** [comment]
Hey @tagur87 

You probably will want to run this again with `BOXEN_DEV_MODE` env var to anything > 0 then check out the temp build directory. That output looks reasonably promising -- boxen runs a local http server on port 6666 serving up the disk image. The build dockerfile uses curl to yoink that disk into the build context (it does this to have small build context up front -- there were issues w/ large qcows making the build context super big and slow). So it looks like we are getting at least to that point.

If you run w/ the dev mode, that tmp directory will still exist and you can check to confirm the dockerfile(s) look good and the disk image is in there and all that. Then you could just run `python -m http.server 6666` and the build the image to see if it is able to yoink that file down w/out boxen wrapping it. Should be able to begin troubleshooting it that way. Hope that helps!?

Carl

**Comment by carlmontanari** [comment]
Just a quick update on this: looks like I ran into this trying to package a CSR1000v as well. I started adding some prints and such to see just where it got hung but then every subsequent build ran! So.... not 100% clear what is going on here, but it looks like it is happening somewhere in [here](https://github.com/carlmontanari/boxen/blob/main/boxen/boxen/packagebuild.go#L237-L263). Not sure yet what is happening though since I would expect an error on the socket listen if there was something wrong, not blocking indefinitely... just putting this out here for posterity/in case anyone else sees it...

**Comment by carlmontanari** [comment]
Genuinely no idea why, but it does seem like the 0.0.1-alpha release sorted this. Can't explain it at the moment, but if you can give that a crack that'd be great @tagur87 !

**Comment by tagur87** [comment]
Thanks again for the help!  Looks like I get a bit further now on v0.0.1, but now I am getting another error about accelleration.

Any insight? 

```
panic: no preferred acceleration type(s) available

goroutine 50 [running]:
github.com/carlmontanari/boxen/boxen/instance.(*Qemu).launchCmdAccel(0xc000212000, 0xc0000bb4e0, 0x0, 0xc0001701d8)
        /home/runner/work/boxen/boxen/boxen/instance/qemulaunchcmd.go:75 +0x1b6
github.com/carlmontanari/boxen/boxen/instance.(*Qemu).buildLaunchCmd(0xc000212000)
        /home/runner/work/boxen/boxen/boxen/instance/qemu.go:111 +0xe5
github.com/carlmontanari/boxen/boxen/instance.(*Qemu).Start(0xc000212000, 0xc00019c170, 0x2, 0x2, 0x407155, 0xc0002a2000)
        /home/runner/work/boxen/boxen/boxen/instance/qemu.go:156 +0xa5
github.com/carlmontanari/boxen/boxen/platforms.(*JuniperVsrx).Install.func1(0xc0002684b0, 0xc00019c170, 0x2, 0x2, 0xc00019c140, 0xc000194060, 0xc000192138, 0xc0001c0000)
        /home/runner/work/boxen/boxen/boxen/platforms/junipervsrx.go:91 +0x6a
created by github.com/carlmontanari/boxen/boxen/platforms.(*JuniperVsrx).Install
        /home/runner/work/boxen/boxen/boxen/platforms/junipervsrx.go:90 +0x285
```

**Comment by carlmontanari** [comment]
Ah this seems easier to address (hopefully) :)

What os are you running boxen on? If Darwin then yeah, won't be able to build (package into a container) vSRX because it requires KVM or HAXM -- but you can only use HAXM locally ("vm" mode, not packaging mode), and Darwin won't have KVM available in containers. If you are *not* on Darwin (I'm going to assume linux because I have no intention of supporting windows in any way shape or form 😁 ) then you'll need to make sure you have nested virtualization/kvm support on your machine.

**Comment by tagur87** [comment]
Yea, i am on MacOS/darwin. That explains it. I can try to build on something with nested virtualization support then. Thanks for the help.

**Comment by carlmontanari** [comment]
No problemo! If you think it can/should boot w/out acceleration (in my experience w/ the older vsrx image I have it does not want to, but could be my setup or older version or whatever), you can override the "profile" with the `--profile` flag pointing to a yaml file that looks like [this](https://github.com/carlmontanari/boxen/blob/main/boxen/assets/profiles/juniper_vsrx.yaml), but with `none` added to the list of preferred accelerations. You could also install HAX and try it locally (vm mode) just to confirm that boxen does what it should w/ the newer disk image/initial config/etc.!

Carl
